
      var CURRENT_REPORT_TYPE = "<?= (typeof initialType !== 'undefined' ? initialType : 'FIRST') ?>";
      var INITIAL_AUTO_RUN = "<?= (typeof initialAutoRun !== 'undefined' ? initialAutoRun : '0') ?>";
      var BUILD_INFO = "<?= (typeof buildInfo !== 'undefined' ? buildInfo : 'unknown-build') ?>";
      var LAST_RENDERED_DATA = null, LAST_RESPONSE_META = "none", ITEMS_EXPANDED = false, PROMOTIONS_EXPANDED = false;
      var params = new URLSearchParams(window.location.search || ""); var isDebug = params.get("debug") === "1";
      var FALLBACK_REPORT_DATA = { client_name:"", report_type:"FIRST", generated_at:"", kpis:{ recurring_net:0, recurring_fees:0, recurring_value:0, optimized_net:null, unlock:null }, actions:[], promotions:[], portfolio:{ cards:[], totals:{ annual_fees:0, value:0, net:0 } } };
      function safeText(s){ return String(s==null?"":s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;"); }
      function formatUsd(n){ var x=Number(n); if(isNaN(x)) x=0; var a=Math.round(Math.abs(x)).toString().replace(/\B(?=(\d{3})+(?!\d))/g,","); return x<0?"-$"+a:"$"+a; }
      function formatUsdOrDash(n){ if(n==null||n==="") return "—"; var x=Number(n); if(isNaN(x)) return "—"; return formatUsd(x); }
      function formatIso(iso){ var d=new Date(iso||""); if(isNaN(d.getTime())) return "-"; return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0")+" "+String(d.getHours()).padStart(2,"0")+":"+String(d.getMinutes()).padStart(2,"0"); }
      function setStatus(t){ var n=document.getElementById("statusText"); if(n) n.textContent=t||"Ready"; renderDebug(LAST_RENDERED_DATA); }
      function setLoading(id,l,a,b){ var btn=document.getElementById(id); if(!btn) return; btn.disabled=!!l; if(a&&b) btn.textContent=l?a:b; }
      function showDebug(m,e){ var d=e?(e.stack?String(e.stack):(e.message?String(e.message):String(e))):""; LAST_RESPONSE_META="error: "+String(m||"unknown")+(d?(" | "+d):""); renderDebug(LAST_RENDERED_DATA); }
      function reportTypeLabel(t){ return String(t||"FIRST").toUpperCase()==="MONTHLY"?"MONTHLY":"FIRST"; }
      function cacheKey(type){ return "beautiful_report_cache_v1_" + reportTypeLabel(type); }
      function readCachedDto(type){ try { var raw=sessionStorage.getItem(cacheKey(type)); if(!raw) return null; return normalizeDto(JSON.parse(raw)); } catch(e){ return null; } }
      function writeCachedDto(dto){ try { sessionStorage.setItem(cacheKey(dto.report_type), JSON.stringify(dto)); } catch(e){} }
      function normalizeDto(raw){ var d=raw||{}, k=d.kpis||{}, p=d.portfolio||{}, t=p.totals||{}, a=Array.isArray(d.actions)?d.actions.slice():[]; a.sort(function(x,y){ var xp=Number(x&&x.priority); if(isNaN(xp)) xp=999; var yp=Number(y&&y.priority); if(isNaN(yp)) yp=999; return xp-yp; }); return { client_name:d.client_name||"Lumina Logic LLC", report_type:reportTypeLabel(d.report_type), generated_at:d.generated_at||"", kpis:{ recurring_net:Number(k.recurring_net)||0, recurring_fees:Number(k.recurring_fees)||0, recurring_value:Number(k.recurring_value)||0, optimized_net:(k.optimized_net==null?null:(Number(k.optimized_net)||0)), unlock:(k.unlock==null?null:(Number(k.unlock)||0)) }, actions:a, promotions:Array.isArray(d.promotions)?d.promotions.slice():[], portfolio:{ cards:Array.isArray(p.cards)?p.cards.slice():[], totals:{ annual_fees:Number(t.annual_fees)||0, value:Number(t.value)||0, net:Number(t.net)||0 } } }; }
      function applyToolbarMode(){ if(isDebug) document.body.classList.add("debug-on"); ["runFirstBtn","runMonthlyBtn","reloadBeautifulBtn"].forEach(function(id){ if(!isDebug){ var n=document.getElementById(id); if(n) n.style.display="none"; } }); }
      function renderHeader(dto){ document.getElementById("clientName").textContent=dto.client_name; document.getElementById("reportTypeLabel").textContent=dto.report_type; document.getElementById("generatedAt").textContent=formatIso(dto.generated_at); }
      function renderKpiCards(dto,title){ var sub=dto.kpis.optimized_net==null?'<div class="hero-sub">Not available yet</div>':''; return '<h2 class="section-title">'+safeText(title)+'</h2><div class="hero-grid"><article class="hero-card"><div class="hero-label">Keep current (12-month net)</div><div class="hero-value '+(dto.kpis.recurring_net<0?'neg':'pos')+'">'+safeText(formatUsd(dto.kpis.recurring_net))+'</div></article><article class="hero-card"><div class="hero-label">After fixes (12-month net)</div><div class="hero-value">'+safeText(formatUsdOrDash(dto.kpis.optimized_net))+'</div>'+sub+'</article><article class="hero-card"><div class="hero-label">Unlock (12-month delta)</div><div class="hero-value '+((dto.kpis.unlock||0)>0?'pos':'')+'">'+safeText(formatUsdOrDash(dto.kpis.unlock))+'</div></article></div>'; }
      function renderHero(dto){ var msg=''; if(dto.kpis.recurring_net<0) msg="Right now you're paying fees to lose money. The top fixes below can reverse that over the next 12 months."; else if((dto.kpis.unlock||0)>0) msg="You're doing fine, but leaving money on the table. The top fixes below can unlock more value."; else msg="Your setup looks stable. Keep monitoring and act only when meaningful alerts appear."; document.getElementById("heroSection").innerHTML=renderKpiCards(dto,"Hero (12-month impact)")+'<div class="micro-kpis"><span>Annual Fees: <strong>'+safeText(formatUsd(dto.kpis.recurring_fees))+'</strong></span><span>Estimated Value: <strong>'+safeText(formatUsd(dto.kpis.recurring_value))+'</strong></span></div><div class="hero-message">'+safeText(msg)+'</div>'; }
      function renderMonthlyStatusBanner(dto){ var n=document.getElementById("monthlyBannerSection"); if(dto.report_type!=="MONTHLY"){ n.style.display="none"; n.innerHTML=""; return; } n.style.display=""; n.innerHTML='<h2 class="section-title">Monthly Status Banner</h2><div class="row"><strong>This month: '+safeText(String(dto.actions.length))+' items need attention.</strong></div><div class="row muted">We only alert on loss, pending bonus, fee due, stale data.</div>'; }
      function renderOutlook(dto){ var n=document.getElementById("outlookSection"); if(dto.report_type!=="MONTHLY"){ n.style.display="none"; n.innerHTML=""; return; } n.style.display=""; n.innerHTML=renderKpiCards(dto,"12-month Outlook"); }
      function renderPortfolioSnapshot(dto){ var n=document.getElementById("portfolioSnapshotSection"); if(dto.report_type!=="FIRST"){ n.style.display="none"; n.innerHTML=""; return; } var t=dto.portfolio.totals; n.style.display=""; n.innerHTML='<h2 class="section-title">Portfolio Snapshot</h2><div class="totals"><span>Annual Fees: <strong>'+safeText(formatUsd(t.annual_fees||0))+'</strong></span><span>Estimated Value: <strong>'+safeText(formatUsd(t.value||0))+'</strong></span><span>Net: <strong>'+safeText(formatUsd(t.net||0))+'</strong></span></div>'; }
      function renderCardHealth(dto){ var c=dto.portfolio.cards||[], rows=''; if(!c.length) rows='<tr><td colspan="6" class="muted">No active cards found. Please check your Card_Assets status.</td></tr>'; else rows=c.map(function(x){ return '<tr><td>'+safeText(x.card_name||'')+'</td><td>'+safeText(x.status||'-')+'</td><td class="num">'+safeText(formatUsd(x.annual_fee||0))+'</td><td class="num">'+safeText(formatUsd(x.est_value||0))+'</td><td class="num">'+safeText(formatUsd(x.net||0))+'</td><td>'+safeText(x.lifecycle_stage||'-')+'</td></tr>'; }).join(''); var ttl=dto.report_type==="MONTHLY"?"Card Health (compact table)":"Card Health (table)"; document.getElementById("cardHealthSection").innerHTML='<h2 class="section-title">'+safeText(ttl)+'</h2><div class="table-wrap"><table><thead><tr><th>Card</th><th>Status</th><th class="num">Annual Fee</th><th class="num">Value</th><th class="num">Net</th><th>Lifecycle</th></tr></thead><tbody>'+rows+'</tbody></table></div>'; }
      function renderItems(dto){ var l=Array.isArray(dto.actions)?dto.actions:[], v=ITEMS_EXPANDED?l:l.slice(0,3), b=''; if(!l.length) b="<div class=\"item muted\">No urgent actions. We'll keep monitoring.</div>"; else b='<div class="list">'+v.map(function(a){ var pr=(a.priority==null||a.priority==='')?'-':String(a.priority); return '<article class="item"><div class="item-top"><span class="pill">P'+safeText(pr)+'</span><span class="muted">'+safeText(a.issue_type||'')+'</span></div><div class="row"><strong>'+safeText(a.card_name||'')+' - '+safeText(a.title||'')+'</strong></div><div class="row muted">'+safeText(a.status||'')+'</div><div class="row">Action: '+safeText(a.action||'')+'</div><div class="row">Impact: <strong>'+safeText(formatUsd(a.impact_usd||0))+'</strong></div></article>'; }).join('')+'</div>'; var tg=l.length>3?'<button id="itemsToggle" class="toggle">'+(ITEMS_EXPANDED?'Show fewer':('Show all ('+l.length+')'))+'</button>':''; var t=dto.report_type==="MONTHLY"?"This Month's Actions":"Priority Actions"; document.getElementById("itemsSection").innerHTML='<h2 class="section-title">'+safeText(t)+'</h2>'+b+tg; var n=document.getElementById("itemsToggle"); if(n) n.onclick=function(){ ITEMS_EXPANDED=!ITEMS_EXPANDED; renderItems(dto); }; }
      function renderPortfolio(dto){ var n=document.getElementById("portfolioSection"); if(dto.report_type!=="MONTHLY"){ n.style.display="none"; n.innerHTML=""; return; } var c=dto.portfolio.cards||[], t=dto.portfolio.totals, r=''; if(!c.length) r='<tr><td colspan="6" class="muted">No active cards found. Please check your Card_Assets status.</td></tr>'; else r=c.map(function(x){ return '<tr><td>'+safeText(x.card_name||'')+'</td><td>'+safeText(x.status||'-')+'</td><td class="num">'+safeText(formatUsd(x.annual_fee||0))+'</td><td class="num">'+safeText(formatUsd(x.est_value||0))+'</td><td class="num">'+safeText(formatUsd(x.net||0))+'</td><td>'+safeText(x.lifecycle_stage||'-')+'</td></tr>'; }).join(''); n.style.display=""; n.innerHTML='<h2 class="section-title">Portfolio</h2><div class="totals"><span>Annual Fees: <strong>'+safeText(formatUsd(t.annual_fees||0))+'</strong></span><span>Estimated Value: <strong>'+safeText(formatUsd(t.value||0))+'</strong></span><span>Net: <strong>'+safeText(formatUsd(t.net||0))+'</strong></span></div><div class="table-wrap"><table><thead><tr><th>Card</th><th>Status</th><th class="num">Annual Fee</th><th class="num">Value</th><th class="num">Net</th><th>Lifecycle</th></tr></thead><tbody>'+r+'</tbody></table></div>'; }
      function renderPromotions(dto){ var l=Array.isArray(dto.promotions)?dto.promotions:[], v=PROMOTIONS_EXPANDED?l:l.slice(0,3), b=''; if(!l.length) b='<div class="item muted">No active promotions.</div>'; else b='<div class="list">'+v.map(function(p){ var link=p.affiliate_url?('<a class="link" target="_blank" rel="noopener" href="'+safeText(p.affiliate_url)+'">Open link</a>'):'<span class="muted">No link</span>'; return '<article class="item"><div class="row"><strong>'+safeText(p.promo_headline||p.card_name||'Promotion')+'</strong></div><div class="row muted">Bonus: '+safeText(formatUsd(p.bonus_value_est_usd||0))+' | End date: '+safeText(p.promo_end_date||'-')+'</div><div class="row">'+link+'</div></article>'; }).join('')+'</div>'; var tg=l.length>3?'<button id="promotionsToggle" class="toggle">'+(PROMOTIONS_EXPANDED?'Show fewer':('Show all ('+l.length+')'))+'</button>':''; var t=dto.report_type==="FIRST"?"Best Offers (Promotions)":"Promotions"; document.getElementById("promotionsSection").innerHTML='<h2 class="section-title">'+safeText(t)+'</h2>'+b+tg; var n=document.getElementById("promotionsToggle"); if(n) n.onclick=function(){ PROMOTIONS_EXPANDED=!PROMOTIONS_EXPANDED; renderPromotions(dto); }; }
      function renderCompareStrip(dto){ var n=document.getElementById("compareStripSection"); if(dto.report_type!=="FIRST"){ n.style.display="none"; n.innerHTML=""; return; } n.style.display=""; n.innerHTML='<h2 class="section-title">If you do nothing vs If you act</h2><div class="row">Keep current: <strong>'+safeText(formatUsd(dto.kpis.recurring_net))+'</strong></div><div class="row">After fixes: <strong>'+safeText(formatUsdOrDash(dto.kpis.optimized_net))+'</strong></div><div class="row">Unlock: <strong>'+safeText(formatUsdOrDash(dto.kpis.unlock))+'</strong></div>'; }
      function renderNextActions(dto){ var l=Array.isArray(dto.actions)?dto.actions.slice(0,2):[], h='<h2 class="section-title">Next Actions</h2>'; if(!l.length) h+='<ul class="next-list"><li>Next: No action needed. Recheck next month.</li></ul>'; else h+='<ul class="next-list">'+l.map(function(a){ return '<li>Next: '+safeText(a.action||'Review item')+' ('+safeText(a.card_name||'Card')+')</li>'; }).join('')+'</ul>'; document.getElementById("nextActionsSection").innerHTML=h; }
      function renderFooter(){ document.getElementById("footerSection").innerHTML='<h2 class="section-title">Footer</h2><div class="row">12-month net = estimated value - annual fees (recurring only).</div><div class="row">Optimized net and unlock are estimates based on suggested actions.</div>'; }
      function renderLoadingState(type){
        var t = reportTypeLabel(type);
        document.getElementById("clientName").textContent = "Credit Card Health Check Report";
        document.getElementById("reportTypeLabel").textContent = t;
        document.getElementById("generatedAt").textContent = "Preparing...";
        document.getElementById("heroSection").innerHTML = '<h2 class="section-title">Hero (12-month impact)</h2><div class="skeleton"></div><div class="skeleton" style="margin-top:8px;"></div>';
        ["monthlyBannerSection","outlookSection","portfolioSnapshotSection","cardHealthSection","itemsSection","portfolioSection","promotionsSection","compareStripSection","nextActionsSection","footerSection"].forEach(function(id){
          var n=document.getElementById(id);
          if(!n) return;
          n.style.display="";
          n.innerHTML='<div class="skeleton"></div>';
        });
      }
      function buildEmailBody(dto){ var lines=[]; lines.push(dto.client_name+' - '+dto.report_type+' - Generated '+formatIso(dto.generated_at)); lines.push(''); lines.push('12-month numbers'); lines.push('- Keep current: '+formatUsd(dto.kpis.recurring_net)); lines.push('- After fixes: '+formatUsdOrDash(dto.kpis.optimized_net)); lines.push('- Unlock: '+formatUsdOrDash(dto.kpis.unlock)); lines.push(''); lines.push('Top actions'); var a=(dto.actions||[]).slice(0,3); if(!a.length) lines.push('- No urgent actions.'); else a.forEach(function(x,i){ lines.push((i+1)+'. P'+(x.priority==null?'-':String(x.priority))+' '+(x.card_name||'Card')+' - '+(x.action||'Review')); }); lines.push(''); lines.push('Portfolio totals: Fees '+formatUsd(dto.portfolio.totals.annual_fees||0)+' | Value '+formatUsd(dto.portfolio.totals.value||0)+' | Net '+formatUsd(dto.portfolio.totals.net||0)); lines.push(''); lines.push('Promotions'); var p=(dto.promotions||[]).slice(0,3); if(!p.length) lines.push('- No active promotions.'); else p.forEach(function(x,i){ lines.push((i+1)+'. '+(x.promo_headline||x.card_name||'Promotion')+' (end: '+(x.promo_end_date||'-')+')'); }); lines.push(''); lines.push('12-month net = estimated value - annual fees (recurring only).'); lines.push('Optimized net and unlock are estimates based on suggested actions.'); return lines.join('\\n'); }
      function copyEmailBody(){ var dto=LAST_RENDERED_DATA||normalizeDto(FALLBACK_REPORT_DATA), text=buildEmailBody(dto); if(navigator.clipboard&&navigator.clipboard.writeText){ navigator.clipboard.writeText(text).then(function(){ setStatus('Email body copied'); }).catch(function(e){ showDebug('copy failed',e); setStatus('Copy failed'); }); return; } var ta=document.createElement('textarea'); ta.value=text; document.body.appendChild(ta); ta.select(); try{ document.execCommand('copy'); setStatus('Email body copied'); }catch(e){ showDebug('copy failed',e); setStatus('Copy failed'); } document.body.removeChild(ta); }
      function renderDebug(dto){ if(!isDebug) return; var t=document.getElementById("debugText"); if(!t) return; t.textContent=["buildInfo: "+BUILD_INFO,"url: "+String(window.location.href),"CURRENT_REPORT_TYPE: "+String(CURRENT_REPORT_TYPE||""),"lastResponse: "+LAST_RESPONSE_META,"status: "+((document.getElementById("statusText")||{}).textContent||""),"actions: "+String(dto&&dto.actions?dto.actions.length:0)].join("\\n"); }
      function renderAll(data){ var dto=normalizeDto(data||FALLBACK_REPORT_DATA); LAST_RENDERED_DATA=dto; CURRENT_REPORT_TYPE=dto.report_type; renderHeader(dto); renderHero(dto); renderMonthlyStatusBanner(dto); renderOutlook(dto); renderPortfolioSnapshot(dto); renderCardHealth(dto); renderItems(dto); renderPortfolio(dto); renderPromotions(dto); renderCompareStrip(dto); renderNextActions(dto); renderFooter(); renderDebug(dto); writeCachedDto(dto); }
      function loadData(){
        setStatus("Loading preview...");
        if(!window.google||!google.script||!google.script.run){
          var fb=readCachedDto(CURRENT_REPORT_TYPE) || FALLBACK_REPORT_DATA;
          renderAll(fb);
          setStatus("Offline preview");
          LAST_RESPONSE_META="mock";
          return;
        }
        var cached = readCachedDto(CURRENT_REPORT_TYPE);
        if(cached){
          renderAll(cached);
          setStatus("Showing latest snapshot, refreshing...");
        } else {
          renderLoadingState(CURRENT_REPORT_TYPE);
        }
        google.script.run.withSuccessHandler(function(data){ LAST_RESPONSE_META="ok,type="+(data&&data.report_type?data.report_type:"n/a"); renderAll(data||FALLBACK_REPORT_DATA); setStatus("Preview updated"); }).withFailureHandler(function(err){ LAST_RESPONSE_META="error"; if(!cached) renderAll(FALLBACK_REPORT_DATA); setStatus("Using latest available snapshot"); showDebug("loadData failed",err); }).getBeautifulReportData("Lumina Logic LLC",CURRENT_REPORT_TYPE);
      }
      function runFirst(){ CURRENT_REPORT_TYPE="FIRST"; loadData(); }
      function runMonthly(){ CURRENT_REPORT_TYPE="MONTHLY"; loadData(); }
      function todayStamp(){ var d=new Date(); return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0"); }
      function reportTypeShort(t){ return String(t||"FIRST").toUpperCase()==="MONTHLY"?"Monthly":"First"; }
      function downloadPdf(){ setStatus("Building PDF..."); setLoading("downloadBtn",true,"Building...","Download PDF"); var n=document.querySelector("#reportRoot"), c=(LAST_RENDERED_DATA&&LAST_RENDERED_DATA.client_name)?LAST_RENDERED_DATA.client_name:"Lumina Logic LLC", f=reportTypeShort(CURRENT_REPORT_TYPE)+"_"+c+"_"+todayStamp()+".pdf"; if(!n||typeof html2pdf==="undefined"){ setLoading("downloadBtn",false,"Building...","Download PDF"); showDebug("downloadPdf unavailable"); return; } html2pdf().set({ margin:8, filename:f, image:{ type:"jpeg", quality:0.98 }, html2canvas:{ scale:2, useCORS:true }, jsPDF:{ unit:"mm", format:"a4", orientation:"portrait" }, pagebreak:{ mode:["css","legacy"] } }).from(n).save().then(function(){ setLoading("downloadBtn",false,"Building...","Download PDF"); setStatus("PDF downloaded"); }).catch(function(err){ setLoading("downloadBtn",false,"Building...","Download PDF"); setStatus("PDF failed"); showDebug("downloadPdf failed",err); }); }
      function initPage(){ try{ applyToolbarMode(); document.getElementById("downloadBtn").addEventListener("click",downloadPdf); CURRENT_REPORT_TYPE=reportTypeLabel(CURRENT_REPORT_TYPE); renderLoadingState(CURRENT_REPORT_TYPE); loadData(); }catch(e){ showDebug("init failed",e); } }
      window.addEventListener("error",function(evt){ showDebug("window.onerror", evt&&(evt.error||evt.message||evt)); }); window.onunhandledrejection=function(evt){ showDebug("unhandledrejection", evt&&evt.reason?evt.reason:evt); };
      if(document.readyState==="loading") document.addEventListener("DOMContentLoaded",initPage); else initPage();
    
